sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - echo ${EXAMPLE}
  - docker login -u="${DOCKERHUB_USERNAME}" -p="${DOCKERHUB_PASSWORD}"

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: build
      script: ./build-and-push.py
