language: python
python:
  - "3.6"

sudo: required

services:
  - docker

before_install:
  - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: build
      script: docker 
      script: ./build-and-push.py
