language: python

sudo: required

services:
  - docker

before_install:
  - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"

jobs:
  include:
    - stage: build
      script: docker 
      script: ./build-and-push.py
