name: Build and Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          wget --output-document nomad-1.5.6.tar.gz https://github.com/hashicorp/nomad/archive/v1.5.6.tar.gz
          docker build --tag hendrikmaus/nomad-cli:1.5.6-testbuild .
          docker push hendrikmaus/nomad-cli:1.5.6-testbuild

